---
abstract: "provides a Catalyst-like \"stash\" method for your class"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Object::Stash
name: Object-Stash
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Hash::FieldHash: 0
  Scalar::Util: 0
  Sub::Name: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Object-Stash
  homepage: https://metacpan.org/release/Object-Stash
  license: http://dev.perl.org/licenses/
version: 0.003
